version: "3.9"   
services:
  traefik:
    image: traefik:latest
    command: 
      - "--providers.docker=true"
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports: 
      - "80:80"
      - "7000:7000"
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend-projects/traefik/data/traefik.yml:/traefik.yml:ro
    labels:
      - "traefik.enable=true"
   

      

  backend:
    build: ./backend-projects
    ports:
      - "8000:5000"
    command: "sh -c 'uvicorn backend_projects.main:app --reload --workers 1 --host 0.0.0.0 --port 5000'"
    expose: 
      - "5000"

    volumes:
      - ./backend-projects:/backend_projects

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=Host(`backend.${LOCAL_1}`, `backend.${LOCAL_2}`, `backend.${EXT_ENDPOINT1}`)"
      - traefik.http.services.backend.loadbalancer.server.port=5000
 

#creacion del dockerfile, version, servicios utilizados en este proyecto, donde se instalara el dockerfile (build) donde se ejecutara el proyecto (ports)
#commando para ejecucion del servidor en el puerto 500 y volumes es en donde se copiaran los archivos al ejecutar el command 